name: admob
description: Admob SDK for Flutter.
version: 0.0.4
repository: https://github.com/volskaya/flutter_helpers
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.22.0"

dependencies:
  flutter:
    sdk: flutter

  freezed_annotation: ^0.14.1
  json_annotation: ^4.1.0
  mobx: ^2.0.0-nullsafety.5
  flutter_mobx: ^2.0.0-nullsafety.3
  mobx_codegen: ^2.0.0-nullsafety.2

  loader_coordinator:
    path: /home/projects/packages/flutter_helpers/loader_coordinator
  log:
    path: /home/projects/packages/flutter_helpers/log
  refresh_storage:
    path: /home/projects/packages/flutter_helpers/refresh_storage
  utils:
    path: /home/projects/packages/flutter_helpers/utils
  await_route:
    path: /home/projects/packages/flutter_helpers/await_route

dev_dependencies:
  build_runner:
  json_serializable: ^5.0.0
  freezed: ^0.14.1+1

dependency_overrides:
  freezed_annotation:
    path: /home/projects/forks/freezed/packages/freezed_annotation
  freezed:
    path: /home/projects/forks/freezed/packages/freezed
  mobx_codegen:
    path: /home/projects/forks/mobx.dart/mobx_codegen

flutter:
  plugin:
    platforms:
      android:
        package: dev.volskaya.admob
        pluginClass: AdmobPlugin
      ios:
        pluginClass: AdmobPlugin
